dist: trusty
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy3"
matrix:
  include:
  - python: 3.7
    dist: xenial
  - python: 3.8
    dist: xenial
  - python: 3.9
    dist: xenial
  - python: pypy
    dist: xenial
  - python: pypy3
    dist: xenial
services: mongodb
before_install:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.7 ]]; then pip install "pip<22" setuptools; else pip install --upgrade pip setuptools; fi
install:
  - if [[ $TRAVIS_PYTHON_VERSION == pypy* ]]; then pip install "tinydb<4"; fi
  - pip install "pymongo<4"
  - pip install -r requirements.py2.txt
  - pip install -r extra.py2.txt
  - if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then pip install coveralls; fi
env:
  - ADAPTER=mongo HTTPBIN=httpbin.bemisc.com
  - ADAPTER=tiny HTTPBIN=httpbin.bemisc.com
script: if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then coverage run --source=quorum setup.py test; else python setup.py test; fi
after_success: if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then coveralls; fi
