sudo: false
dist: trusty
language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
  - "pypy-5.3.1"
  - "pypy-5.4.1"
  - "pypy-5.6.0"
  - "pypy-5.7.1"
  - "pypy3-2.4.0"
  - "pypy2.7-5.8.0"
  - "pypy3.5-5.8.0"
services: mongodb
before_install:
  - if [[ $TRAVIS_PYTHON_VERSION != "3.2" ]] && [[ $TRAVIS_PYTHON_VERSION != "3.3" ]] && [[ $TRAVIS_PYTHON_VERSION != "pypy3-2.4.0" ]]; then pip install --upgrade pip setuptools; fi
  - if [[ $TRAVIS_PYTHON_VERSION == "3.2" ]]; then pip install --upgrade "pip<8.0" "setuptools<20.0"; fi
  - if [[ $TRAVIS_PYTHON_VERSION == "3.3" ]] || [[ $TRAVIS_PYTHON_VERSION == "pypy3-2.4.0" ]]; then pip install --upgrade "pip<10.0" "setuptools<24.0"; fi
install:
  - if [[ $TRAVIS_PYTHON_VERSION == "pypy3" ]]; then pip install "flask<0.11"; fi
  - pip install "pkginfo<1.3"
  - pip install -r requirements.txt
  - pip install -r extra.txt
  - pip install "pycparser<2.19" coveralls
env:
  - ADAPTER=mongo HTTPBIN=httpbin.bemisc.com
  - ADAPTER=tiny HTTPBIN=httpbin.bemisc.com
script: if [[ $TRAVIS_PYTHON_VERSION != "3.2" ]]; then coverage run --source=quorum setup.py test; else python setup.py test; fi
after_success: if [[ $TRAVIS_PYTHON_VERSION != "3.2" ]]; then coveralls; fi
deploy:
  provider: pypi
  user: joamag
  password:
    secure: CJ2EKdJCjwsVNoByH2C0FXztMJRo1iWgQw3etfMD5aDa0KdyI8cg/VZHDaEYQ3z5IBepRYPXN7eipjCvJpEJPAylQWzzyJUgSUOyNDQHDBfUAe0Mp9ODrNHZPjGnZIWSOAOY1+yHXSo5p8CIgnRuAhnq9KazSfXhqTUx6yoV5IY=
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: "2.7"
    condition: $ADAPTER = mongo
