sudo: false
language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly"
  - "pypy"
  - "pypy3"
services: mongodb
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install twine
script: if [[ $TRAVIS_PYTHON_VERSION != "3.2" ]]; then coverage run --source=quorum setup.py test; else python setup.py test; fi
after_success: coveralls
deploy:
  provider: pypi
  user: joamag
  password:
    secure: CQhwl6lT1Yn4PDvLwCLBZqy+zAPzOi+Xg+wNseTuy4kAiUsTsUVk6nfbOvdTwa7TELMKLyLWN6UJjEXrrCzDxItpDZ9oY8wz+K8KmWzWx8TaW6PerFrR1taczdWCezSuu+ctvBmTmQJkObnzB3y6qwx19bWfpqWWkzoNVuPvdpo=
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: "2.7"
