sudo: false
language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
  - "pypy3"
services: mongodb
install:
  - pip install -r requirements.txt
  - pip install coveralls
script: coverage run --source=quorum setup.py test
after_success: coveralls
